title: AICL Co-pilot Documentation
description: Official documentation for the AICL Co-pilot Framework
theme: just-the-docs
#remote_theme: just-the-docs/just-the-docs  #just-the-docs

#plugins:
  #- jekyll-remote-theme

# Color scheme supports "light" (default) and "dark"
color_scheme: light

url: https://yuushabio.github.io/
baseurl: aicl-copilot-doc/

defaults:
  - scope:
      path: "docs" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "default"

callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false