title: AICL Co-pilot Documentation
description: Official documentation for the AICL Co-pilot Framework
remote_theme: pmarsceill/just-the-docs  #just-the-docs

plugins:
  - jekyll-remote-theme

# Color scheme supports "light" (default) and "dark"
color_scheme: light

url: https://yuushabio.github.io/aicl-copilot-doc

defaults:
  - scope:
      path: "docs" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "default"